// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wbqoyjljdsayyfgfibif.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndicW95amxqZHNheXlmZ2ZpYmlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzODA0NzAsImV4cCI6MjA2OTk1NjQ3MH0.WJ3TZ3UWJSrI3nIqFp211ttTV9reBZx4lWxPUT0u9xY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});